name: Update steam playtime

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "5 * * * *"

jobs:
  build:
    name: Update-steam-playtime
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: 441944f130dd5c4f3aee8056c837f8e6
      STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      STEAM_ID: ${{ secrets.STEAM_ID }}
      UPDATE_OPTION: GIST_AND_MARKDOWN
      MARKDOWN_FILE: README.md

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Clone and run steam-box
        run: |-
          git clone https://github.com/zhy617/steam-box.git 
          cd steam-box && go build -o steam ./cmd/box/main.go
          mv ./steam ../ && cd .. && rm -rf steam-box/
      - name: Debug Secrets
        run: |-
          echo "GH_TOKEN: ${{ secrets.GH_TOKEN }}"
          echo "STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}"
          echo "STEAM_ID: ${{ secrets.STEAM_ID }}"

      - name: Commit and push
        env:
          # 使用 GH_TOKEN 进行身份验证
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |-
          ./steam
          git config --global user.email "bot@github.com" && git config --global user.name "Steam-Bot"
          git diff
          git add README.md && git commit -m ":memo: update profile" || exit 0
          git pull && git push
